# Generated by Django 5.0.1 on 2024-01-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('E', 'Electronics'), ('C', 'Clothing'), ('HK', 'Home and Kitchen'), ('B', 'Books'), ('S&O', 'Sports and Outdoors'), ('B&PC', 'Beauty and Personal Care'), ('T&G', 'Toys and Games'), ('F', 'Furniture'), ('A', 'Automotive'), ('H&W', 'Health and Wellness'), ('G', 'Grocery'), ('J', 'Jewelry'), ('NONE', 'UNAVIALABLE')], default='NONE', max_length=10),
        ),
    ]
