# Generated by Django 5.0.1 on 2024-01-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0004_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
